package:
  name: apk-tools
  version: 2.12.9
  epoch: 1
  description: "apk-tools (Wolfi package manager)"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-2.0-only
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    repositories:
      - https://mirrors.edge.kernel.org/alpine/edge/main
      - https://storage.googleapis.com/disaster-exercise-wolfi-production-registry-destination/bootstrap/stage1
    keyring:
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-58199dcc.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-616ae350.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-616adfeb.rsa.pub
      - https://storage.googleapis.com/disaster-exercise-wolfi-production-registry-destination/bootstrap/stage1/wolfi-signing.rsa.pub
    packages:
      - alpine-baselayout
      - busybox
      - perl
      - make
      - ca-certificates-bundle
      - scdoc
      - cross-gcc-stage1
      - cross-binutils-stage1
      - cross-glibc-stage1
      - cross-linux-headers
      - cross-openssl
      - cross-pkgconf
      - cross-zlib

pipeline:
  - uses: fetch
    with:
      uri: https://gitlab.alpinelinux.org/alpine/apk-tools/-/archive/v${{package.version}}/apk-tools-v${{package.version}}.tar.gz
      expected-sha256: 7d9f68683c282a8e30a119e7951ffee293ec2caa8d55fd1280841eda09825ddd
  - runs: |
      sed -i -e 's:-Werror::' Make.rules
      echo "FULL_VERSION=${{package.version}}-r${{package.epoch}}" > config.mk
  - runs: |
      make LUA="no" AR="${{cross.triplet.gnu.glibc}}-ar" \
        CC="${{cross.triplet.gnu.glibc}}-gcc" PKG_CONFIG="${{cross.triplet.gnu.glibc}}-pkg-config" V=1
  - runs: |
      make LUA="no" AR="${{cross.triplet.gnu.glibc}}-ar" \
        CC="${{cross.triplet.gnu.glibc}}-gcc" PKG_CONFIG="${{cross.triplet.gnu.glibc}}-pkg-config" V=1 \
        DESTDIR="${{targets.destdir}}" \
        install

      install -d "${{targets.destdir}}"/var/lib/apk
      install -d "${{targets.destdir}}"/var/cache/misc
      install -d "${{targets.destdir}}"/etc/apk/keys
      install -d "${{targets.destdir}}"/etc/apk/protected_paths.d
