package:
  name: bison
  version: 3.8.2
  epoch: 0
  description: "The GNU general-purposes parser generator"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:
      - m4

environment:
  contents:
    repositories:
      - https://mirrors.edge.kernel.org/alpine/edge/main
      - https://storage.googleapis.com/disaster-exercise-wolfi-production-registry-destination/bootstrap/stage1
    keyring:
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-58199dcc.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-616ae350.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-616adfeb.rsa.pub
      - https://storage.googleapis.com/disaster-exercise-wolfi-production-registry-destination/bootstrap/stage1/wolfi-signing.rsa.pub
    packages:
      - alpine-baselayout
      - busybox
      - perl
      - ca-certificates-bundle
      - cross-gcc-stage1
      - cross-binutils-stage1
      - cross-glibc-stage1
      - cross-linux-headers
      - perl
      - m4

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/bison/bison-${{package.version}}.tar.gz
      expected-sha256: 06c9e13bdf7eb24d4ceb6b59205a4f67c2c7e7213119644430fe82fbd14a0abb
  - name: 'Configure bison'
    runs: |
      ./configure \
        --prefix=/usr \
        --libdir=/lib \
        --sysconfdir=/etc \
        --datadir=/usr/share \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --host=${{cross.triplet.gnu.glibc}} \
        --target=${{cross.triplet.gnu.glibc}}
  - runs: |
      make -j$(nproc) V=1
  - uses: autoconf/make-install
  - runs: |
      rm -rf "${{targets.destdir}}"/usr/lib
  - uses: strip
