package:
  name: mpfr
  version: 4.1.0
  epoch: 1
  description: "multiple-precision floating-point library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: LGPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://mirrors.edge.kernel.org/alpine/edge/main
      - https://storage.googleapis.com/disaster-exercise-wolfi-production-registry-destination/bootstrap/stage1
    keyring:
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-58199dcc.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-616ae350.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-616adfeb.rsa.pub
      - https://storage.googleapis.com/disaster-exercise-wolfi-production-registry-destination/bootstrap/stage1/wolfi-signing.rsa.pub
    packages:
      - alpine-baselayout
      - busybox
      - build-base
      - ca-certificates-bundle
      - texinfo
      - cross-gcc-stage1
      - cross-binutils-stage1
      - cross-glibc-stage1
      - cross-libstdc++-stage1
      - cross-linux-headers
      - cross-gmp

pipeline:
  - uses: fetch
    with:
      uri: https://www.mpfr.org/mpfr-${{package.version}}/mpfr-${{package.version}}.tar.xz
      expected-sha256: 0c98a3f1732ff6ca4ea690552079da9c597872d30e96ec28414ee23c95558a7f
  - runs: |
      ./configure \
        --host=${{cross.triplet.gnu.glibc}} \
        --target=${{cross.triplet.gnu.glibc}} \
        --with-sysroot=/usr/${{cross.triplet.gnu.glibc}} \
        --prefix=/usr \
        --enable-shared
  - uses: autoconf/make
  - uses: autoconf/make-install
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info

subpackages:
  - name: "cross-mpfr"
    pipeline:
      - runs: |
          make install DESTDIR="${{targets.subpkgdir}}/usr/${{cross.triplet.gnu.glibc}}"
      - name: 'Clean up documentation'
        runs: |
          rm -rf ${{targets.subpkgdir}}/usr/${{cross.triplet.gnu.glibc}}/usr/share/info
    options:
      no-provides: true
      no-depends: true
      no-commands: true
